version: 2.1
jobs:
  test-app:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      - run:
          name: "Install deps"
          command: "npm ci"
      - run:
          name: "Run tests"
          command: "npm test"
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  fb-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "FB test job"
          command: "echo Hello From Branch: ${CIRCLE_BRANCH}"

# Invoke jobs via workflows
workflows:
  test-app:
    jobs:
      - test-app
      - say-hello:
          requires:
            - test-app
      - fb-hello:
          filters:
            branches:
              only: /^feature\/.*$/
